apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bonus-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.merkol.com/root/InceptionOfThings.git
    targetRevision: HEAD
    path: confs/playground
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
