Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"   
 
  config.vm.define "merkolS" do |control|
	control.vm.hostname = "merkolS"
	control.vm.network "private_network", ip: "192.168.56.110"
	control.vm.synced_folder ".", "/vagrant", disabled: false
	control.vm.provider "virtualbox" do |v|
			v.name = "merkolS"
	     	v.gui = false
	     	v.memory = "1024"
	     	v.cpus = 1
		end
	control.ssh.insert_key = false
	control.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
	control.vm.provision "shell", path: "provision.sh", args: "control"
	end
	
  config.vm.define "merkolSW" do |agent|
	agent.vm.hostname = "merkolSW"
	agent.vm.network "private_network", ip: "192.168.56.111"
	agent.vm.synced_folder ".", "/vagrant", disabled: false
	agent.vm.provider "virtualbox" do |v|
			v.name = "merkolSW"
			v.gui = false
	     	v.memory = "1024"
	     	v.cpus = 1
		end
	agent.ssh.insert_key = false
	agent.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
	agent.vm.provision "shell", path: "provision.sh", args: "agent"
	end  
end
