apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-p3
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/merkol42/iot-p3-merkol.git
    targetRevision: HEAD
    path: config
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: will-app-deployment
#   labels:
#     app: will
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: will
#   template:
#     metadata:
#       labels:
#         app: will
#     spec:
#       containers:
#       - name: will
#         image: wil42/playground:v1
#         ports:
#         - containerPort: 8888

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: will-app-service
#   labels:
#     app: will
# spec:
#   type: LoadBalancer
#   selector:
#       app: will
#   ports:
#     - protocol: TCP
#       port: 8888
#       targetPort: 8888
